### PR TITLE
css-canvas-medical

### PR DESCRIPTION
**Pull request by AndyPark20**
Before Revision
*******************************************************************************************************************************
image
image
image
**************************************************************************************************************************************

After Revision
************************************************************************************************************************************
image
image
image

***************************************************************************************************************************************

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Looking great!

Here is the feedback I have: 

Feedback for Canvas Medical
For the Nav: 
	looks solid
For the image: 
	The text block should have slightly larger text and slightly greater line height
	Should be wider in relation to the page
For the clinician section:
	text should be slightly larger
	spacing between the two columns of text should be increased
Ready to learn section:
	text should be lighter
	vertical alignment should be adjust between text and button
Footer:
	looks solid
Bottom links:
	element should be slightly less tall

**Comment by AndyPark20** [comment]
Good evening Brett!

Thank you very much for your feedback!
I have made the following changes 

1. Image:
   - Text block font size has been increased & line height has also been increased
   -  Made image wider in relation to the page

2. Clinician Section:
   - Text has been slightly increased
   - Space between columns have been further extended.

3. Ready to learn Section:
   - Lighter Text weight has been implemented.
   - Vertical alignment between text and the "Get Started" button has been centered

4. Bottom Links:
   - Narrowed the height of the container element box to make the element less tall

**Comment by AndyPark20** [comment]
************************************************************
                                                           Product Page
************************************************************
image
image
image
image
image

***********************************************************
                                                           Implementation Page
***********************************************************
image
image
image
image
image

***********************************************************
                                                           About Us Page
***********************************************************
image
image
image
image
image
image
image

***********************************************************
                                                           Blog Page
***********************************************************
image
image
image

***********************************************************
                                                           Contact Us Page
***********************************************************
image
image

**Review by Zhiwutian — APPROVED** [review]
👍

**Pull request merged**
